apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: devopnerd-com-tls
spec:
  secretName: devopnerd-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devopnerd.com
  dnsNames:
    - devopnerd.com
    - www.devopnerd.com